"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.Admin=Core.Agent.Admin||{};Core.Agent.Admin.GenericAgent=(function(TargetNS){function AddSelectClearButton(){var $SelectFields=$('select'),ModernizeActive=parseInt(Core.Config.Get('InputFieldsActivated'),10);$SelectFields.each(function(){var Size=parseInt($(this).attr('size'),10),ModernizeField=$(this).hasClass('Modernize'),$SelectField=$(this),SelectID=this.id,Multiple=$(this).attr('multiple'),ButtonHTML='<a href="#" title="'+Core.Language.Translate('Remove selection')+'" class="GenericAgentClearSelect" data-select="'+SelectID+'"><span>'+Core.Language.Translate('Remove selection')+'</span><i class="fa fa-undo"></i></a>';if(ModernizeActive&&ModernizeField){return;}
if((isNaN(Size)&&!Multiple)||Size<=1){return;}
if($SelectField.next('a.ShowTreeSelection').length){$SelectField=$SelectField.next('a.ShowTreeSelection');}
$SelectField.after(ButtonHTML);});$('.GenericAgentClearSelect').on('click.ClearSelect',function(){var SelectID=$(this).data('select'),$SelectField=$('#'+SelectID);if(!$SelectField.length){return false;}
$SelectField[0].selectedIndex=-1;$(this).blur();return false;});}
TargetNS.Init=function(){$('.DeleteEvent').on('click',function(Event){TargetNS.ShowDeleteEventDialog(Event,$(this));return false;});$('#GenericAgentJobs a.TrashCan').on('click',function(){if(window.confirm(Core.Language.Translate('Do you really want to delete this generic agent job?'))){return true;}
return false;});$('#TicketEvent').on('change',function(){if($('#EventType').val()!==null){TargetNS.AddEvent($('#EventType').val());}});$('#ArticleEvent').on('change',function(){if($('#EventType').val()!==null){TargetNS.AddEvent($('#EventType').val());}});$('#EventType').on('change',function(){TargetNS.ToggleEventSelect($(this).val());Core.UI.InputFields.Activate($('.EventTypeName'));});TargetNS.ToggleEventSelect($('#EventType').val());Core.UI.Table.InitTableFilter($("#FilterGenericAgentJobs"),$("#GenericAgentJobs"));AddSelectClearButton();};TargetNS.ToggleEventSelect=function(SelectedEventType){$('.EventList').parent().hide();$('#'+SelectedEventType+'Event').parent().show();};TargetNS.AddEvent=function(EventType){var $Clone=$('.EventRowTemplate').clone(),EventName=$('#'+EventType+'Event').val(),IsDuplicated=false;if(!EventName){return;}
$('[class*=EventValue]').each(function(){if($(this).val()===EventName){IsDuplicated=true;}});if(IsDuplicated){TargetNS.ShowDuplicatedDialog('EventName');return;}
$Clone.find('.EventType').html(EventType);$Clone.find('.EventName').html(EventName);$Clone.find('.EventValue').attr('name','EventValues').val(EventName);$Clone.find('#DeleteEvent').on('click',function(Event){TargetNS.ShowDeleteEventDialog(Event,$(this));return false;});$Clone.removeClass('Hidden EventRowTemplate');$('#EventsTable > tbody:last').append($Clone);};TargetNS.ShowDeleteEventDialog=function(Event,Object){Core.UI.Dialog.ShowContentDialog($('#DeleteEventDialogContainer'),Core.Language.Translate('Delete this Event Trigger'),'240px','Center',true,[{Label:Core.Language.Translate('Cancel'),Class:'Primary',Function:function(){Core.UI.Dialog.CloseDialog($('#DeleteEventDialog'));}},{Label:Core.Language.Translate('Delete'),Function:function(){Object.parents('tr:first').remove();Core.UI.Dialog.CloseDialog($('#DeleteEventDialog'));}}]);Event.stopPropagation();Event.preventDefault();};TargetNS.ShowDuplicatedDialog=function(){Core.UI.Dialog.ShowAlert(Core.Language.Translate('Duplicate event.'),Core.Language.Translate('This event is already attached to the job, Please use a different one.'),function(){Core.UI.Dialog.CloseDialog($('.Alert'));$('#EventType').focus();return false;});};Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.Admin.GenericAgent||{}));

